name: Verify PR

on:
  push:

jobs:
  RunOnLinux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Grant Permission
        run: sudo chmod +x ./mvnw
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'
      - name: Run Tests
        run: ./mvnw -B -ntp clean verify
